message_board/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('posts.urls'), name='posts')
]

posts/urls.py
from django.urls import path
from .views import Homeposts ,homeview
urlpatterns = [
    path('post/',homeview.as_view(),name='posts'),
    path('post2/',Homeposts.as_view(), name='postpage2')

]

posts/models.py
from django.db import models

# Create your models here.

class post_model(models.Model):
    author_name = models.CharField(max_length=70)
    psot_title = models.TextField(max_length=150)
    discriptions =models.TimeField(max_length=200)

posts/views.py
# fisrt approch 
from django.views.generic.list import ListView  # fisrt approch 
from .models import post_model



class homeview(ListView):
    model = post_model
    template_name = 'posts/post.html'



# second apprch 
from django.views.generic import TemplateView
from django.shortcuts import render
class Homeposts(TemplateView):
    template_name = 'posts/post2.html'
    def get(self,request ):
        model_data = post_model.objects.all()
        return render(request , self.template_name , {'td':model_data})

posts/templates/posts/post.html
<h1> post Page  </h1>


</ul>



<li>

<table border="1">
<tr>
<th>ID </th>
<th> Aurthor Name </th>
<th> Post Title </th>
<th> Time </th>
</tr>

{% for post in post_model_list  %}
    <tr>
        <td>{{post.id }}</td>
        <td>{{post.author_name }}</td>
        <td>{{post.psot_title }}</td>
        <td>{{post.discriptions }}</td>
    </tr>
{% endfor %}


</table>
</li>

posts/templates/posts/post2.html
<h1> post Page 2   </h1>


</ul>



<li>

<table border="1">
<tr>
<th>ID </th>
<th> Aurthor Name </th>
<th> Post Title </th>
<th> Time </th>
</tr>

{% for post in td  %}
    <tr>
        <td>{{post.id }}</td>
        <td>{{post.author_name }}</td>
        <td>{{post.psot_title }}</td>
        <td>{{post.discriptions }}</td>
    </tr>
{% endfor %}


</table>
</li>

templates/home.html
<h1>home page for post views  </h1>

<ul>
    {% for post in post_model_list  %}
    
        <li>{{post.author_name}}</li>
        <li>{{post.psot_title}}</li>
        
    
    {% endfor %}


</ul>



<li>

<table border="1">
<tr>
<th>ID </th>
<th> Aurthor Name </th>
<th> Post Title </th>
<th> Time </th>
</tr>

{% for post in post_model_list  %}
    <tr>
        <td>{{post.id }}</td>
        <td>{{post.author_name }}</td>
        <td>{{post.psot_title }}</td>
        <td>{{post.discriptions }}</td>
    </tr>
{% endfor %}


</table>
</li>